name: Push for build

on:
  push:
    branches:
      - 'automatic_exe_build'
jobs:
  build-windows:
    name: Executable build for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          C:\Miniconda\condabin\conda.bat env create -f conda_environment.yml
          C:\Miniconda\condabin\conda.bat init powershell
      - name: Avoid MKL dependence
        run: |
          C:\Miniconda\condabin\conda.bat install -c conda-forge nomkl numpy pandas pyqt pyinstaller
          C:\Miniconda\condabin\conda.bat install -c bioconda pyteomics
      - name: Get current directory information
        run: |
          dir
      - name: Build exe
        run: |
          .\gui_tools\build_gui.bat