name: Push for build

on:
  push:
    branches:
      - 'automatic_exe_build'

    #jobs:
    #  build:
    #    name: 'Build .exe for Windows users'
    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        python-version: [ '3.8' ]
    #    runs-on: 'windows-latest'


    #    defaults:
    #      run:
    #        shell: bash -l {0}
    #        steps:
    #          - run: |
    #              conda env create -f conda_environment.yml
    #              build_gui.bat


jobs:
  build-windows:
    name: Executable build for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Echo help to check working conda functionality
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          & $CONDA/bin/conda --help
          & $CONDA/bin/conda env list
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file conda_environment.yml --name base