name: Push for build

on:
  push:
    branches:
      - 'automatic_exe_build'
jobs:
  build-windows:
    name: Executable build for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download UPX and unpack
        run: |
          mkdir UPX
          curl -L https://github.com/upx/upx/releases/tag/v3.96/upx-3.96-win64.zip --output .\UPX\upx-3.96-win64.zip
          Expand-Archive C:\UPX\upx-3.96-win64.zip -DestinationPath .\UPX\upx-3.96\
      - name: Install dependencies
        run: |
          C:\Miniconda\condabin\conda.bat env create -f conda_environment.yml
          C:\Miniconda\condabin\conda.bat init powershell
          C:\Miniconda\condabin\conda.bat activate simsi_transfer_gui
      - name: Avoid MKL dependence
        run: |
          C:\Miniconda\condabin\conda.bat install -c conda-forge nomkl numpy pandas pyqt pyinstaller
          C:\Miniconda\condabin\conda.bat install -c bioconda pyteomics
      - name: Build exe and compress with UPX
        run: |
          cd .\gui_tools
          build_gui.bat
      - name: Add built .exe to release
        run: |
          echo "There is stuff missing here..."