name: Push for build

on:
  push:
    branches:
      - 'automatic_exe_build'

    #jobs:
    #  build:
    #    name: 'Build .exe for Windows users'
    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        python-version: [ '3.8' ]
    #    runs-on: 'windows-latest'


    #    defaults:
    #      run:
    #        shell: bash -l {0}
    #        steps:
    #          - run: |
    #              conda env create -f conda_environment.yml
    #              build_gui.bat


jobs:
  build-linux:
    name: Poetry build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]
        poetry-version: [ 1.1.11 ]
        os: [ ubuntu-20.04 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Build package
        run: poetry build
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file conda_environment.yml --name base